accounts/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
  PasswordResetView, 
  PasswordResetDoneView, 
  PasswordResetConfirmView,
  PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup_view, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('profile', views.view_profile, name='profile'),
  path('profile/', views.view_profile, name='view_profile'),
  path('profile/edit', views.edit_profile, name='edit_profile'),
  path('change-password', views.change_password, name='change_password'),
  path('reset-password', PasswordResetView.as_view(), name='reset_password'),
  path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
  url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

  
  #path('profile/', views.user_recipes, name='user_recipes'),
  #path("recipes/", include('recipes.urls')),
  
]

foodify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include('pages.urls')),
    path("recipes/", include('recipes.urls')),
    path("accounts/", include('accounts.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name ='pages'

urlpatterns = [
  path("", views.index, name='recipes'),
  path("about/", views.about, name='about'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipe_app'

urlpatterns = [
  path('', views.index, name='recipes'),
  path('<int:recipe_id>', views.recipe, name='recipe'),
  path('create/', views.recipe_create, name='create'),
  #path('userrecipes/', views.user_recipes, name='user_recipes'),
  path("search", views.search, name='search'),
]

templates/partials/_footer.html
<section id="footer" class="bg-light p-2 mt-5">
    <div class="container text-center mt-5">
        <h3>FOODIFY</h3>
        <p>Copyright &copy; <span id="year"></span></p>
    </div>
</section>

templates/partials/_navbar.html
<!-- Navbar-->
<nav class="navbar navbar-expand-sm bg-light navbar-light">
    <div class="container">

      <!-- hamburger menu -->
      {% if user.is_authenticated %}
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'pages:recipes' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'recipe_app:recipes' %}" class="nav-link">Recipes</a>
              </li>
            <li class="nav-item">
              <a href="{% url 'pages:about' %}" class="nav-link">About</a>
            </li>
          </ul>
        </div>
      {% else %}
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a href="{% url 'pages:recipes' %}" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'pages:about' %}" class="nav-link">About</a>
              </li>
            </ul>
          </div>   
      {% endif %}

      

      {% if user.is_authenticated %}
      <h5>logged in as: <span style="color:darkcyan"><a href="{% url 'accounts:profile' %}">{{ request.user }}</a></span></h5>
        <form action="{% url 'accounts:logout' %}" class="form-group" method="post">
          {% csrf_token %}
          <a href="{% url 'recipe_app:create' %}" class="ml-2 mt-3">New Recipe</a>
          <a href="{% url 'accounts:edit_profile' %}" class="ml-2 mt-3">Edit Profile</a>
          <a href="{% url 'accounts:change_password' %}" class="ml-2 mt-3">Change Password</a>
          <a href="{% url 'accounts:reset_password' %}" class="ml-2 mt-3">Reset Password</a>
          <button class="btn btn-dark ml-2 mt-3" type="submit">Logout</button>
        </form>
      {% else %}
        <form class="form-inline">
          <a class="btn btn-primary mr-2" href="{% url 'accounts:profile' %}">Log In</a>
          <a href="{% url 'accounts:signup' %}" class="btn btn-success mr-2">Sign Up</a>
          <a href="{% url 'accounts:reset_password' %}">Forgot Password?</a>
        </form>
      {% endif %}


    </div>
  </nav>

