accounts/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
  PasswordResetView, 
  PasswordResetDoneView, 
  PasswordResetConfirmView,
  PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup_view, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
  path('profile', views.view_profile, name='profile'),
  path('profile/', views.view_profile, name='view_profile'),
  path('profile/edit', views.edit_profile, name='edit_profile'),
  path('change-password', views.change_password, name='change_password'),
  path('reset-password', PasswordResetView.as_view(), name='reset_password'),
  path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
  url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

  
  #path('profile/', views.user_recipes, name='user_recipes'),
  #path("recipes/", include('recipes.urls')),
  
]

foodify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include('pages.urls')),
    path("recipes/", include('recipes.urls')),
    path("accounts/", include('accounts.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name ='pages'

urlpatterns = [
  path("", views.index, name='recipes'),
  path("about/", views.about, name='about'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipe_app'

urlpatterns = [
  path('', views.index, name='recipes'),
  path('<int:recipe_id>', views.recipe, name='recipe'),
  path('create/', views.recipe_create, name='create'),
  #path('userrecipes/', views.user_recipes, name='user_recipes'),
  path("search", views.search, name='search'),
]

accounts/models.py
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    about = models.TextField(blank=True)
    location = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    profile_photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.all().create(user=kwargs['instance'])




    
post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.db import models
from . import models
from .models import UserProfile

# class SignUpForm(UserCreationForm):
#     class Meta:
#         model = UserImage
#         fields = ('photo_profile',)


# photo_profile   = models.ImageField(upload_to='photos/%Y/%m/%d')


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

class PhotoProfileUpload(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_photo',)
        

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    UserChangeForm, 
    PasswordChangeForm
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash #this session we wanted to continue even after we change the password and redirect the user

from recipes.models import Recipe
from accounts.forms import EditProfileForm, PhotoProfileUpload
#from .forms import SignUpForm


# creates user signup form
def signup_view(request):
    if request.method == 'POST':
        #passing data in an instance of UserCreationForm and validate if the data is valid
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # save to db
            user = form.save()

            #log user in
            login(request, user)
            return redirect('accounts:profile')
    else: #if request method is GET
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)




def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():

            #log in user
            user = form.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('recipe_app:recipes')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('recipe_app:recipes')




# User Profile
@login_required(login_url="/accounts/login/")
def view_profile(request):
    logged_in_user_posts = Recipe.objects.filter(author=request.user)
    context = {
        'posts': logged_in_user_posts,
    }
    #args = {'user': request.user}
    return render(request, 'accounts/profile.html', context)


# @login_required(login_url="/accounts/login/")
# def view_profile(request, recipe_id):
#     logged_in_user_posts = Recipe.objects.filter(author=request.user)
#     recipe = get_object_or_404(Recipe, pk=recipe_id)
#     context = {
#         'posts': logged_in_user_posts,
#         'recipe':recipe
#     }
#     #args = {'user': request.user}
#     return render(request, 'accounts/profile.html', context)


@login_required(login_url="/accounts/login/")
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:

        form = EditProfileForm(instance=request.user)
        context = {
            'form': form,
            }
        return render(request, 'accounts/edit_profile.html', context)



# @login_required(login_url="/accounts/login/")
# def edit_profile(request):
#     if request.method == 'POST':
#         form = EditProfileForm(request.POST, instance=request.user)
#         photo_upload_form = PhotoProfileUpload(request.POST, request.FILES)
        
#         if form.is_valid() and photo_upload_form.is_valid():
#             form.save()
#             photo_upload_form.save()
#             return redirect('accounts:profile')
#     else:

#         form = EditProfileForm(instance=request.user)
#         photo_upload_form = PhotoProfileUpload(instance=request.user)
#         context = {
#             'form': form,
#             'photo_upload_form': photo_upload_form
#             }
#         return render(request, 'accounts/edit_profile.html', context)




# def upload_file(request):
#     if request.method == 'POST':
#         photo_upload_form = PhotoProfileUpload(request.POST, request.FILES)

#         if photo_upload_form.is_valid():
#             photo_upload_form.save()
#             return redirect('accounts:profile')
#     else:
#         photo_upload_form = PhotoProfileUpload()
#     return render(request, 'accounts/edit_profile.html', {'photo_upload_form': photo_upload_form})




def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        context = {'form': form}
        return render(request, 'accounts/change_password.html', context)

templates/accounts/change_password.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<nav class="navbar navbar-expand py-5">
        <div class="container">
            <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
        </div>
    </nav>

    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Update</button>
        </form>
    </div>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<nav class="navbar navbar-expand py-5">
        <div class="container">
            <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
        </div>
    </nav>

    <div class="container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            {{ photo_upload_form }}
            <button type="submit">Update</button>
        </form>
    </div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<nav class="navbar navbar-expand py-5">
    <div class="container">
        <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
    </div>
</nav>

    <div class="container">
        <h1>Log in</h1>
        <form action="{% url 'accounts:login' %}" class="form-group" method="post">
            {% csrf_token %}
            {{ form|crispy }}

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            
            <input type="submit" class="form-control btn btn-primary" value="Login">
        </form>
    </div>
    
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Navbar 2-->

    <!-- Navbar 2-->
<nav class="navbar navbar-expand py-5">
        <div class="container">
          <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
          <form class="form-group" action="{% url 'recipe_app:search' %}">
            <div class="input-group mt-5">
                <input class="form-control" type="text" placeholder="Search Recipe" name="keywords" value="{{ values.keywords }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
          </form>
          
        </div>
      </nav>

    <div class="container">
        <h3 class="display-5">Profile</h3>
        <div>
            {% if user.userprofile.profile_photo %}
                <img src="{{ user.userprofile.profile_photo.url }}" alt="" class="main-profile-img">
            {% else %}
                <img src="{% static 'img/white.png' %}">
            {% endif %}
        </div>
        <p>Username: <span style="color: darkcyan;">{{ user }}</span></p>
        <p>First name: <span style="color: darkcyan;">{{ user.first_name }}</span></p>
        <p>Last name: <span style="color: darkcyan;">{{ user.last_name }}</span></p>
        <p>Email: <span style="color: darkcyan;">{{ user.email }}</span></p>

        <p>Description: {{ user.userprofile.description }}</p>
        <p>About: {{ user.userprofile.about }}</p>
        <p>Location: {{ user.userprofile.location }}</p>
        <p>Website: <a href="{{ user.userprofile.website }}">{{ user.userprofile.website }}</a></p>
    

     <!-- Main Section -->
        <h1>Your Recipes</h1>
        <div class="row mb-5 mt-5">
                {% for post in posts %}
            <div class="col-lg-4">
                <div>
                    <img src="{{ post.photo_main.url }}" alt="" class="img-fluid">
                </div>
                <h4>{{ post.title }}</h4>
                <p class="text-muted">{{ post.list_date }}</p>
                <p class="lead">{{ post.body|truncatechars:140 }}</p>
              
            </div>
            {% endfor %}     
        </div>
    </div>
        
    

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<nav class="navbar navbar-expand py-5">
        <div class="container">
            <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
        </div>
    </nav>

    <div class="container">
        <h1>Sign Up</h1>
        <form action="{% url 'accounts:signup' %}" class="form-group" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ photo_upload_form }}
            <input type="submit" class="form-control btn btn-primary" value="Signup">
        </form>
    </div>
    
{% endblock %}