foodify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include('pages.urls')),
    path("recipes/", include('recipes.urls')),
    path("accounts/", include('accounts.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name ='pages'

urlpatterns = [
  path("", views.index, name='recipes'),
  path("about/", views.about, name='about'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipe_app'

urlpatterns = [
  path('', views.index, name='recipes'),
  path('<int:recipe_id>', views.recipe, name='recipe'),
  path('create/', views.recipe_create, name='create'),
  #path('userrecipes/', views.user_recipes, name='user_recipes'),
  path("search", views.search, name='search'),
]

recipes/models.py
from django.db import models

from django.conf import settings
from datetime import datetime

from django.contrib.auth.models import User

# class UserProfile(models.Model):
#     Name = models.CharField(max_length=200)
#     About = models.TextField(blank=True)


class Recipe(models.Model):
  #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, default=1)
  title        = models.CharField(max_length=200)
  body         = models.TextField(blank=True)
  photo_main   = models.ImageField(upload_to='photos/%Y/%m/%d')
  is_published = models.BooleanField(default=True)
  list_date    = models.DateTimeField(default=datetime.now, blank=True)
  author       = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
  
  
  def __str__(self):
    return self.title

recipes/forms.py
from django import forms
from . import models

class CreateRecipe(forms.ModelForm):
    class Meta:
        model = models.Recipe
        fields = ['title', 'body', 'photo_main']

recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect

from .models import Recipe
from django.contrib.auth.decorators import login_required
from . import forms
#from django.contrib.auth.models import User
from accounts.models import UserProfile

def index(request):
  recipes = Recipe.objects.order_by('-list_date').filter(is_published=True)

  context = {
    'recipes': recipes
  }

  return render(request, 'recipes/recipes.html', context)




def recipe(request, recipe_id):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  context = {
    'recipe':recipe
  }
  return render(request, 'recipes/recipe.html', context)




@login_required(login_url="/accounts/login/")
def recipe_create(request):
  if request.method == 'POST':
    form = forms.CreateRecipe(request.POST, request.FILES)
    if form.is_valid():
          
      #save recipe to db
      instance = form.save(commit=False)
      instance.author = request.user
      instance.save()
      return redirect('accounts:profile')   
  else:      
    form = forms.CreateRecipe()

  context = {
    'form': form
  }
  return render(request, 'recipes/recipe_create.html', context)

def search(request):
  #return render(request, 'recipes/search.html')
  queryset_list = Recipe.objects.all().order_by('-list_date')

  # Keywords
  if 'keywords' in request.GET:
    keywords = request.GET['keywords']
    if keywords:
        queryset_list = queryset_list.filter(title__icontains=keywords)

  context = {
      'recipes': queryset_list,
      'values': request.GET  #perserving form input
  }

  return render(request, 'recipes/search.html', context)


 
def all_photos(request):
  main_photos = Recipe.objects.filter(is_published=True)

  context = {
    'main_photos': main_photos
  }

  return render(request, 'recipes/recipe.html', context)


templates/recipes/recipe.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- Navbar 2-->
<nav class="navbar navbar-expand py-5">
    <div class="container">
      <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
    </div>
  </nav>

  
<section id="recipe">
    <div class="container">
      <div class="card p-5">
                <div class="media">
                  {% if user.userprofile.profile_photo %}
                    {% for profile_photo in userprofile.profile_photo.all %}
                      <img src="{{ profile_photo.profile_photo.url }}"  class="prof-img mr-3">
                    {% endfor %}
                  {% endif %}
                  <div class="media-body m-3">
                    <p class="card-text">By: {{ recipe.author }}</p>
                <p class="card-text text-dark"><small>{{ recipe.list_date }}</small></p>
                  </div>
                </div>
                
            <img class="card-img-top" src="{{ recipe.photo_main.url }} " alt="">
            <div class="card-body">
                <h4 class="card-title">{{ recipe.title }}</h4>
                <p class="card-text">{{ recipe.body}}</p>
                
            </div>
        </div>
    </div>
    
  </section>
{% endblock %}

templates/recipes/recipe_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<nav class="navbar navbar-expand py-5">
        <div class="container">
          <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
        </div>
</nav>


    <div class="container">
        <h2>Create New Recipe</h2>
        <form action="{% url 'recipe_app:create' %}" class="form-group" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary btn-block">Create</button>
        </form>
    </div>
{% endblock %}

templates/recipes/recipes.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block content %}
<!-- Navbar 2-->
<nav class="navbar navbar-expand py-5">
    <div class="container">
      <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
      <form class="form-group" action="{% url 'recipe_app:search' %}">
        <div class="input-group mt-5">
            <input class="form-control" type="text" placeholder="Search Recipe" name="keywords" value="{{ values.keywords }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
      </form>
      
    </div>
  </nav>

  <!-- Main Section -->
  <section id="main-section">
      <div class="container">

        <!-- Grid -->
        <h2>All Recipes</h2>
        <div class="row mb-5">
          {% if recipes %}
            {% for recipe in recipes %}
            <div class="col-lg-4">
                <div>
                  <img src="{{ recipe.photo_main.url }}" alt="" class="img-fluid">
                </div>
                <h5 class="mt-2">By: {{ recipe.author }}</h5>
                  <p class="text-muted">{{ recipe.list_date }}</p>
                <h3>{{ recipe.title }}</h1>
                  <p>{{ recipe.body|truncatechars:140 }}</p>
                  <a href="{% url 'recipe_app:recipe' recipe.id %}" class="btn btn-danger">Read More</a>
  
            </div>
            {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Available Recipes</p>
          </div>
          {% endif %}

          </div>

      </div>
    </section>
{% endblock %}

templates/recipes/search.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block content %}
<!-- Navbar 2-->
<nav class="navbar navbar-expand py-5">
    <div class="container">
      <a href="{% url 'recipe_app:recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
      <form class="form-group" action="{% url 'recipe_app:search' %}">
        <div class="input-group mt-5">
            <input class="form-control" type="text" placeholder="Search Recipe" name="keywords" value="{{ values.keywords }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search</button>
            </div>
        </div>
      </form>
      
    </div>
  </nav>

  <!-- Main Section -->
  <section id="main-section">
      <div class="container">

        <!-- Grid -->
        <h2>All Recipes</h2>
        <div class="row mb-5">
          {% if recipes %}
            {% for recipe in recipes %}
            <div class="col-lg-4">
                <div>
                  <img src="{{ recipe.photo_main.url }}" alt="" class="img-fluid">
                </div>
                <h5 class="mt-2">By: {{ recipe.author }}</h5>
                  <p class="text-muted">{{ recipe.list_date }}</p>
                <h3>{{ recipe.title }}</h1>
                  <p>{{ recipe.body|truncatechars:140 }}</p>
                  <a href="{% url 'recipe_app:recipe' recipe.id %}" class="btn btn-danger">Read More</a>
  
            </div>
            {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Available Recipes</p>
          </div>
          {% endif %}

          </div>

      </div>
    </section>
{% endblock %}

templates/recipes/user_recipes.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block content %}
<!-- Navbar 2-->
<nav class="navbar navbar-expand py-5">
    <div class="container">
      <a href="{% url 'recipes' %}" class="navbar-brand text-warning"><h1 class="display-5">FOODIFY</h1></a>
      <form class="form-group">
        <div class="input-group mt-5">
            <input class="form-control" type="text" placeholder="Search Recipe">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button">Search</button>
            </div>
        </div>
      </form>
      
    </div>
  </nav>

  <!-- Main Section -->
  <section id="main-section">
      <div class="container">

        <!-- Grid -->
        <h2>All Recipes</h2>
        <div class="row mb-5">
          {% if recipes.user %}
            {% for recipe in recipes %}
            <div class="col-lg-4">
                <div>
                  <img src="{{ recipe.photo_main.url }}" alt="" class="img-fluid">
                </div>
                <h5 class="mt-2">By: {{ recipe.author }}</h5>
                  <p class="text-muted">{{ recipe.list_date }}</p>
                <h3>{{ recipe.title }}</h1>
                  <p>{{ recipe.body|truncatechars:140 }}</p>
                  <a href="{% url 'recipe' recipe.id %}" class="btn btn-danger">Read More</a>
  
            </div>
            {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Available Recipes</p>
          </div>
          {% endif %}

          </div>

      </div>
    </section>
{% endblock %}